name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Stop and Verify Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          debug: true
          script: |
            set -x  # 모든 명령어 출력
            
            echo "Finding Java processes..."
            PIDS=$(pgrep -f "java -jar" || true)
            
            if [ ! -z "$PIDS" ]; then
              echo "Processes found: $PIDS"
              for PID in $PIDS; do
                echo "Killing process $PID"
                sudo kill -9 $PID || true
              done
              sleep 3
            else
              echo "No processes found"
            fi
            
            echo "Final process check:"
            pgrep -f "java -jar" || true
            
            exit 0
    
      - name: Verify application stopped
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          debug: true
          script: |     
            APP_DIR=~/backend

            cd $APP_DIR

            chmod +x gradlew
            ./gradlew build -x test
            sleep 5
            nohup java -jar build/libs/tts_vc_web-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
        
