name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Stop Existing Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e 
            PIDS=$(sudo ps aux | grep "java -jar" | grep -v grep | awk '{print $2}')
            if [ ! -z "$PIDS" ]; then
              echo "Found Java processes: $PIDS"
              for PID in $PIDS; do
                echo "Attempting to stop process $PID"
                sudo kill -SIGTERM $PID || sudo kill -9 $PID || true
              done
              sleep 5
            else
              echo "No Java processes found"
            fi
            sudo ps aux | grep "java -jar" || true
            exit 0 
      - name: Build and Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |     

            APP_DIR=~/backend
            cd $APP_DIR
            git pull origin main
            chmod +x gradlew
            ./gradlew clean build -x test
            nohup java -jar build/libs/tts_vc_web-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
            sleep 5


