name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Stop Existing Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 더 안전한 프로세스 종료 방식
            pkill -f "java -jar" || true
            sleep 3

      - name: Build and Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |     
            APP_DIR=~/backend
            cd $APP_DIR

            # 최신 코드 pull
            git pull origin main

            # gradlew 권한 설정
            chmod +x gradlew

            # 빌드 (테스트 제외)
            ./gradlew clean build -x test

            # 새 애플리케이션 실행
            nohup java -jar build/libs/tts_vc_web-0.0.1-SNAPSHOT.jar > app.log 2>&1 &

            # 잠시 대기 후 프로세스 확인
            sleep 5
            pgrep -f "java -jar"
