name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Stop Existing Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 상세 로깅 및 오류 핸들링
            set -e  # 스크립트에서 오류 발생 시 즉시 종료
            
            echo "Stopping existing Java applications..."
            
            # 현재 실행 중인 Java 프로세스 확인
            PIDS=$(sudo ps aux | grep "java -jar" | grep -v grep | awk '{print $2}')
            
            if [ ! -z "$PIDS" ]; then
              echo "Found Java processes: $PIDS"
              for PID in $PIDS; do
                echo "Attempting to stop process $PID"
                sudo kill -SIGTERM $PID || sudo kill -9 $PID || true
              done
              
              # 프로세스 종료 대기
              sleep 5
            else
              echo "No Java processes found"
            fi
            
            # 최종 프로세스 확인
            echo "Checking remaining Java processes:"
            sudo ps aux | grep "java -jar" || true
            
            exit 0  # 명시적 성공 종료
      - name: Build and Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |     
            APP_DIR=~/backend
            cd $APP_DIR

            # 최신 코드 pull
            git pull origin main

            # gradlew 권한 설정
            chmod +x gradlew

            # 빌드 (테스트 제외)
            ./gradlew clean build -x test

            # 새 애플리케이션 실행
            nohup java -jar build/libs/tts_vc_web-0.0.1-SNAPSHOT.jar > app.log 2>&1 &

            # 잠시 대기 후 프로세스 확인
            sleep 5
            pgrep -f "java -jar"
